// Package docs contains the Swagger documentation for the Event Ticketing System API.
// This file is auto-generated by swag CLI. Run 'swag init -g cmd/server/main.go' to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Create a new user account with email and password",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user with email and password, returns JWT token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns the authenticated user's profile information",
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "Returns a list of all available events",
                "produces": ["application/json"],
                "tags": ["events"],
                "summary": "List all events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Event"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new event with venue, date, pricing, and seats",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["events"],
                "summary": "Create a new event (Admin only)",
                "parameters": [
                    {
                        "description": "Event details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Event"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "Returns details of a specific event",
                "produces": ["application/json"],
                "tags": ["events"],
                "summary": "Get event by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Event"
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events/{id}/seats": {
            "get": {
                "description": "Returns all seats for an event with optional status filter and summary",
                "produces": ["application/json"],
                "tags": ["events"],
                "summary": "Get seats for an event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query",
                        "enum": ["available", "reserved", "sold"]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.SeatsResponse"
                        }
                    }
                }
            }
        },
        "/bookings/reserve": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Reserves a seat for the authenticated user",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["bookings"],
                "summary": "Reserve a seat",
                "parameters": [
                    {
                        "description": "Seat reservation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ReserveSeatRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    },
                    "202": {
                        "description": "Accepted for async processing",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Seat not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bookings/purchase": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Completes the purchase of a reserved booking via Stripe",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["bookings"],
                "summary": "Purchase a booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Idempotency key",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Purchase details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PurchaseBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    }
                }
            }
        },
        "/bookings/my-bookings": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns all bookings for the authenticated user",
                "produces": ["application/json"],
                "tags": ["bookings"],
                "summary": "Get user's bookings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BookingWithDetails"
                            }
                        }
                    }
                }
            }
        },
        "/bookings/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns a specific booking by ID",
                "produces": ["application/json"],
                "tags": ["bookings"],
                "summary": "Get booking by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Booking"
                        }
                    }
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "description": "Cancels a reserved booking and releases the seat",
                "produces": ["application/json"],
                "tags": ["bookings"],
                "summary": "Cancel a booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/venues": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns a list of all venues",
                "produces": ["application/json"],
                "tags": ["venues"],
                "summary": "List all venues",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Venue"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Creates a new venue with name, address, and capacity",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["venues"],
                "summary": "Create a new venue (Admin only)",
                "parameters": [
                    {
                        "description": "Venue details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateVenueRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Venue"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns a list of all registered users",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "List all users (Admin only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/promote": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Promotes a regular user to admin role",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Promote user to admin (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/demote": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Demotes an admin to regular user role",
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Demote admin to user (Admin only)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.RegisterRequest": {
            "type": "object",
            "required": ["email", "password", "full_name"],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": ["user", "admin"]
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "models.Event": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "venue_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "event_date": {
                    "type": "string",
                    "format": "date-time"
                },
                "ticket_price": {
                    "type": "number"
                },
                "total_seats": {
                    "type": "integer"
                },
                "available_seats": {
                    "type": "integer"
                }
            }
        },
        "models.CreateEventRequest": {
            "type": "object",
            "required": ["venue_id", "title", "event_date", "ticket_price", "total_seats"],
            "properties": {
                "venue_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "event_date": {
                    "type": "string",
                    "format": "date-time"
                },
                "ticket_price": {
                    "type": "number"
                },
                "total_seats": {
                    "type": "integer"
                }
            }
        },
        "models.Venue": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "name": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                }
            }
        },
        "models.CreateVenueRequest": {
            "type": "object",
            "required": ["name", "address", "capacity"],
            "properties": {
                "name": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                }
            }
        },
        "models.Booking": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "event_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "seat_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "status": {
                    "type": "string",
                    "enum": ["reserved", "purchased", "cancelled", "expired"]
                },
                "total_amount": {
                    "type": "number"
                },
                "reserved_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "expires_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "models.BookingWithDetails": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "event_title": {
                    "type": "string"
                },
                "seat_number": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "models.ReserveSeatRequest": {
            "type": "object",
            "required": ["event_id", "seat_number"],
            "properties": {
                "event_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "seat_number": {
                    "type": "string",
                    "example": "R1-S5"
                }
            }
        },
        "models.PurchaseBookingRequest": {
            "type": "object",
            "required": ["booking_id"],
            "properties": {
                "booking_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "idempotency_key": {
                    "type": "string"
                }
            }
        },
        "services.SeatsResponse": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "summary": {
                    "$ref": "#/definitions/services.SeatsSummary"
                },
                "seats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Seat"
                    }
                }
            }
        },
        "services.SeatsSummary": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "available": {
                    "type": "integer"
                },
                "reserved": {
                    "type": "integer"
                },
                "sold": {
                    "type": "integer"
                }
            }
        },
        "models.Seat": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "event_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "seat_number": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": ["available", "reserved", "sold"]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter your JWT token (Bearer prefix added automatically)"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Event Ticketing System API",
	Description:      "A high-concurrency event ticketing system with seat booking, Stripe payments, real-time WebSocket updates, and async processing via Redis Streams.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
